### ISSUE TITLE
Sarcasm sample propotion

### ISSUE THREAD

**Issue by Shelly-zzz** [fesvhtr/DocMSU#1]
In docmsu_all.json, does the 'is_sar' key denote sample(news, image) whether or not sarcasm?
I load json file, finding out that there's only about 7000 samples with is_sar = 1, while the paper data statistic shows there are about 30k sample that is sarcasm. I wonder where is going wrong.Thanks.

**Comment by fesvhtr** [comment]
>> In docmsu_all.json, does the 'is_sar' key denote sample(news, image) whether or not sarcasm?
Yes, is_sar=1 denotes this text-image pair is sarcastic.
>> 7k or 30k
As mentioned in DocMSU paper: "We also use GPT-3.5 to augment the text data and discard instances that may include sensitive information". The current version (7k) is the fully manually labeled version before augmentation.

**Comment by fesvhtr** [comment]
Yes, is_sar=1 denotes the img-text pair is sarcastic. As mentioned in paper, we use GPT to augment text data. The current version (7k) is the fully manually labeled version before augmentation.

**Comment by ChoongwonKang** [comment]
The img.zip and anno.zip files contain only 71,828 data points. The dataset is stated to have 102,588 entries. Could you please clarify where the remaining 30,760 entries are located?
